version: 2

config: &config
  working_directory: ~/android-arch-playground

  docker:
  - image: circleci/android:api-28-alpha

  environment:
    TERM: dumb
    JAVA_TOOL_OPTIONS: "-Xmx1g"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"

cache_key: &cache_key
  key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum  "app/build.gradle" }}

jobs:
  build:
    <<: *config
    steps:
    - checkout
    - restore_cache:
        <<: *cache_key
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies

    - run:
        name: Run Tests
        command: ./gradlew lint test ktlintCheck
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/test-results
    - save_cache:
        <<: *cache_key
        paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper